name: Validate PR

on:
  pull_request:
    branches: ["main"]

jobs:
  Validate-Build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        configuration: [Debug, Release]
    uses: ./.github/workflows/Validate_Build.yml
    with:
      os: ${{ matrix.os }}
      configuration: ${{ matrix.configuration }}

  Validate-Tests:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        configuration: [Debug, Release]
    uses: ./.github/workflows/Validate_Tests.yml
    with:
      os: ${{ matrix.os }}
      configuration: ${{ matrix.configuration }}
    secrets:
      # List secrets required for the Tests job
      # For example:
      # MY_TEST_SECRET: ${{ secrets.MY_TEST_SECRET }}
